spring:
  profiles:
    default: local

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_travel_destination
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  access-expiry-millis: ${JWT_ACCESS_EXPIRY_MILLIS}

cloud:
  aws:
    s3:
      bucket: my-travel-destination
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}